# -*- coding: utf-8 -*-
"""
Generate detailed, type-aware test cases for every audited rule that is NOT yet
fully covered (tests != 'Y'), from _traceability_data.ROWS, and inject them into
test-cases.html as 3 area sections (Frameworks / EP / Product) so the existing
_build_test_cases_xlsx.py pipeline folds them into the executable workbook.

Idempotent: replaces anything between the COVERAGE markers on re-run.
Run:  python _gen_coverage.py   then   _build_test_cases_xlsx.py + _merge_results.py
"""
import os, re, html
from collections import OrderedDict
from _traceability_data import ROWS

HERE = os.path.dirname(__file__)
COLS = ['area', 'module', 'type', 'detail', 'brd', 'tests', 'flag', 'note']
rows = [dict(zip(COLS, t)) for t in ROWS]
gap = [r for r in rows if r['tests'] != 'Y']          # not fully covered -> generate a case

def esc(s): return html.escape(str(s or ''))

# rule-type -> (tc data-type, polarity, priority)
TYPEMAP = {
    'validation': ('val', 'neg', 'p1'), 'calc': ('func', 'pos', 'p1'),
    'skip-logic': ('func', 'pos', 'p1'), 'journey': ('func', 'pos', 'p1'),
    'auto-fill': ('func', 'pos', 'p1'), 'permission': ('func', 'pos', 'p1'),
    'auto-fetch': ('func', 'pos', 'p1'), 'dropdown': ('func', 'pos', 'p2'),
    'field': ('func', 'pos', 'p2'), 'data': ('func', 'pos', 'p2'),
    'checkbox': ('func', 'pos', 'p2'), 'scale': ('func', 'pos', 'p1'),
}
TYPE_TITLE = {'validation': 'Validation', 'calc': 'Calculation', 'skip-logic': 'Skip-logic',
              'journey': 'Journey', 'auto-fill': 'Auto-fill', 'auto-fetch': 'Auto-fetch',
              'permission': 'Permission', 'dropdown': 'Dropdown', 'field': 'Field',
              'data': 'Data', 'checkbox': 'Checkbox', 'scale': 'Rating scale'}

def steps_expected(r):
    t, d = r['type'], r['detail']
    if t == 'dropdown':
        s = [f'Open the form and inspect the dropdown: {d}.', 'Select each option; save and reopen.']
        e = f'The option list exactly matches — {d}. Each value is selectable and persists on save; no backend/raw values leak.'
    elif t == 'validation':
        s = [f'Provide input that violates / boundary-tests the rule: {d}.', 'Attempt to save.']
        e = f'Enforced as specified — {d}. A clear, user-friendly message is shown (no raw error class); valid input passes.'
    elif t == 'skip-logic':
        s = [f'Set the driver field to the trigger value described in: {d}.', 'Then reverse it.']
        e = f'Dependent field/section shows/hides/enables exactly per — {d}. Hidden values are cleared so they do not pollute save; reverses correctly.'
    elif t in ('calc',):
        s = [f'Enter representative inputs for: {d}.', 'Observe the computed (read-only) field.']
        e = f'Computed value matches the formula — {d} — to the correct rounding. Field is read-only and visually distinct from inputs, and shows how it is derived.'
    elif t in ('auto-fill', 'auto-fetch'):
        s = [f'Set up the source described in: {d}.', 'Open the dependent form/field.']
        e = f'Value is auto-populated as specified — {d}. The field shows it is fetched from the source form, with a redirect link to it.'
    elif t == 'journey':
        s = [f'Walk the flow as the relevant role: {d}.']
        e = f'Each step behaves as described — {d} — with correct navigation, persistence and role gating.'
    elif t == 'permission':
        s = [f'As the relevant role, attempt the action: {d}.', 'Repeat as a role that should NOT have access.']
        e = f'Access is enforced per — {d}. Authorised role succeeds; unauthorised role is blocked (read-only / hidden / 403).'
    elif t == 'scale':
        s = [f'Exercise the rating scale: {d}.']
        e = f'Scale behaves as specified — {d} — including the legend labels and how unrated values are handled.'
    else:  # field / data / checkbox
        s = [f'Exercise the element: {d}.', 'Save and reopen to confirm persistence.']
        e = f'Element behaves and persists as specified — {d}.'
    return s, e

FLAG_TAG = {'stale': 'Was stale — realigned', 'brd': 'BRD reconcile pending', 'build': 'Not built in repo — confirm'}

# group: area -> module -> [rows]
areas = OrderedDict()
for r in gap:
    areas.setdefault(r['area'], OrderedDict()).setdefault(r['module'], []).append(r)

AREA_META = {
    'Frameworks': ('cov-frameworks', 'COV-FW', 'Coverage — Frameworks'),
    'Entrepreneur Profile': ('cov-ep', 'COV-EP', 'Coverage — Entrepreneur Profile'),
    'Product Form': ('cov-product', 'COV-PR', 'Coverage — Product Form'),
}

seq = 0
parts = ['<!-- COVERAGE-START : auto-generated by _gen_coverage.py from the traceability audit. Do not hand-edit. -->']
for area, mods in areas.items():
    sid, pid, htitle = AREA_META.get(area, ('cov-x', 'COV', f'Coverage — {area}'))
    n_area = sum(len(v) for v in mods.values())
    parts.append(f'<section class="module" id="{sid}">')
    parts.append(f'<h2>{esc(htitle)}<span class="pid">{pid}</span></h2>')
    parts.append(f'<p class="desc">Rule-by-rule coverage generated from the journey-doc + wireframe + BRD traceability audit — one executable check per rule not already covered by a curated scenario. {n_area} cases.</p>')
    for mod, mr in mods.items():
        parts.append(f'<h3>{esc(mod)} <span style="font-weight:400;color:var(--ink-soft)">({len(mr)})</span></h3>')
        for r in mr:
            seq += 1
            dt, pol, pri = TYPEMAP.get(r['type'], ('func', 'pos', 'p2'))
            role = 'CTP' if (r['area'] == 'Entrepreneur Profile' and r['type'] == 'permission') else 'FA / CTP'
            tcid = f'PR-TC-CVR-{seq:04d}'
            title = f"{TYPE_TITLE.get(r['type'], r['type'].title())}: {r['detail']}"
            s_list, exp = steps_expected(r)
            pol_lbl = {'pos': 'Positive', 'neg': 'Negative'}[pol]
            tp_lbl = {'func': 'Functional', 'val': 'Validation', 'ui': 'UI / UX'}[dt]
            steps_html = ''.join(f'<li>{esc(x)}</li>' for x in s_list)
            brdbits = [f"Trace: {esc(r['area'])} / {esc(r['module'])}"]
            if r['note']: brdbits.append(esc(r['note']))
            if r['flag'] in FLAG_TAG: brdbits.append(FLAG_TAG[r['flag']])
            parts.append(
                f'<div class="tc {pol}" data-type="{dt}" data-pol="{pol}" data-pri="{pri}" data-role="{esc(role)}">'
                f'<div class="tc-head"><span class="tc-id">{tcid}</span>'
                f'<span class="tag pol-{pol}">{pol_lbl}</span><span class="tag pri-{pri}">{pri.upper()}</span>'
                f'<span class="tag tp {dt}">{tp_lbl}</span><span class="tag role">{esc(role)}</span></div>'
                f'<div class="tc-title">{esc(title)}</div>'
                f'<div class="tc-body"><span class="label">Steps</span><ol>{steps_html}</ol>'
                f'<div class="exp"><span class="label">Expected</span> {exp}</div>'
                f'<p class="brd">{" &middot; ".join(brdbits)}</p></div></div>')
    parts.append('</section>')
parts.append('<!-- COVERAGE-END -->')
block = '\n'.join(parts)

# ---- inject (idempotent) ----------------------------------------------------
path = os.path.join(HERE, 'test-cases.html')
src = open(path, encoding='utf-8').read()
src = re.sub(r'<!-- COVERAGE-START.*?<!-- COVERAGE-END -->\s*', '', src, flags=re.DOTALL)
idx = src.rfind('</section>')
assert idx != -1, 'no </section> anchor found'
idx += len('</section>')
src = src[:idx] + '\n\n' + block + '\n' + src[idx:]
open(path, 'w', encoding='utf-8', newline='\n').write(src)
print(f'Injected {seq} coverage cases across {len(areas)} areas into test-cases.html')
for area, mods in areas.items():
    print(f'  {area}: {sum(len(v) for v in mods.values())} cases / {len(mods)} modules')
