# -*- coding: utf-8 -*-
# Traceability rules from the journey-doc-anchored audit. One tuple per rule:
# (area, module, type, detail, brd, tests, flag, note)
#   brd/tests in {'Y','P','N'}; flag in {'', 'stale','gap','brd','build'}
# Built up in parts via append; see _build_traceability.py.

ROWS = []

# ===================== FRAMEWORKS — General + Manufacturing/Pricing ==========
ROWS += [
("Frameworks", "— General (all forms)", "skip-logic", "Task tab REMOVED from all framework forms (journey-doc change); Log Book remains", "Y", "N", "", "BRD says 'Task Tab Removed'; Unit Pricing still shows a TASKS tab on staging (live bug)"),
("Frameworks", "— General (all forms)", "field", "Log Book columns: Fessociate (autofill), Entrepreneur (autofill), Task (from master, filtered by framework), Upload/view photo, Comments", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "calc", "Calculated fields visually distinct from inputs + show the formula in plain language", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "calc", "Fetched fields show source form + a redirect link to it", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "skip-logic", "Intervention-need shown in row banner (Existing); Implementation status in row banner (Required)", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "skip-logic", "Product button filters for product-level frameworks (toggle between products)", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "calc", "Summary tab generated once the form is saved for the first time", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "field", "Each Intervention Details tab has Pre- and Post-Intervention comment boxes", "Y", "N", "", ""),
("Frameworks", "— General (all forms)", "dropdown", "Implementation-status chips: Not started / In progress / Completed / On hold", "P", "N", "", "journey-doc wording is 'Not started'; staging shows 'Pending'"),

# ---- Financials / BMC ----
("Frameworks", "Financials / BMC", "dropdown", "Investment Source: Self-funded, Family/Friends, Bank Loan, Govt Scheme, NGO, Other (9)", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "skip-logic", "'Other Source Name' enabled only when Investment Source = Other", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "validation", "Other Source Name required when Source = Other", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "dropdown", "Bookkeeping Level (Level 1 None … Level 5 Digital — 5)", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "dropdown", "Q1 Yes/No; Q3 Frequency (Daily/Weekly/Monthly/Yearly/Occasionally)", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "dropdown", "Task Name — 16 master tasks", "P", "N", "", "BRD does not enumerate the 16 Financials task labels"),
("Frameworks", "Financials / BMC", "calc", "Avg Net Profit = Rev−Exp; Overall Rev = Rev+Add'l; Margin = NP/Overall×100", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "calc", "Growth averages over N months -> KPI tiles + trend", "Y", "P", "", "FIN-002 covers tracker, not avg/trend math"),
("Frameworks", "Financials / BMC", "calc", "BMC EMI = reducing-balance amortisation P*r(1+r)^n/((1+r)^n-1)", "Y", "N", "", "only a flat EMI is tested, and for a different module"),
("Frameworks", "Financials / BMC", "calc", "Contribution/unit; break-even units = ceil((Exp+EMI)/Contribution); rev break-even; 'Not achievable'", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "calc", "Weighted Avg Selling Price = Revenue / Total Quantity", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "calc", "Total Loan = sum of checked loans; amount-weighted blended rate/tenure", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "skip-logic", "'Add to Total' checkbox includes/excludes a loan from total + EMI", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "skip-logic", "Existing Rev/Exp auto-fetch from FA, editable; manual edit sets Overridden flag", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "auto-fill", "Existing Loan 1 & 2 auto-pulled from FA Loan Details", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "auto-fill", "Total Quantity Existing fetched from Production Capacity", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "calc", "Status banner: contribution<=0 bad / qty>=break-even good / else warn", "Y", "N", "", ""),
("Frameworks", "Financials / BMC", "validation", "Total Units Produced > 0 else cost stays 0", "Y", "P", "", "FIN-003 negative-revenue soft-warn only"),
("Frameworks", "Financials / BMC", "calc", "BMC is a break-even calculator (NOT a 9-block Lean Canvas)", "Y", "N", "stale", "FIN-001/UP-002 still describe BMC as a 9-block Lean Canvas — old model; rewrite"),

# ---- Unit Pricing ----
("Frameworks", "Unit Pricing", "dropdown", "Pricing Method: Cost Plus / Competitor Based / Value Based", "Y", "Y", "", ""),
("Frameworks", "Unit Pricing", "dropdown", "Competitor Scope: Local / State / National", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "dropdown", "Positioning: -20/-10/Match/+10/Premium +20..+50 (8)", "Y", "P", "", "only +10% tested"),
("Frameworks", "Unit Pricing", "dropdown", "RM / Labour / Packaging / Machinery row pickers (seeded REF_DATA)", "P", "N", "", "seeded master values not enumerated in BRD"),
("Frameworks", "Unit Pricing", "dropdown", "SKU selector (from Product module)", "P", "N", "", ""),
("Frameworks", "Unit Pricing", "calc", "Row Amount = Qty x Rate; section subtotal = sum of amounts", "Y", "P", "", "UP-001 generic"),
("Frameworks", "Unit Pricing", "auto-fill", "Unit & rate auto-fill from REF_DATA on material select", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "calc", "Transport subtotal = RM transport + Pkg transport", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "calc", "Gas amount = Qty x Rate", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "calc", "Rent/Unit; Electricity/Unit; Others subtotal", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "calc", "Cost per Unit = (Total Input / Units) + Per-Unit Overheads", "Y", "P", "", "exact formula untested"),
("Frameworks", "Unit Pricing", "calc", "Cost Plus: Selling = Cost x (1+Markup); Retail = Selling x (1+RetMargin)", "Y", "Y", "", ""),
("Frameworks", "Unit Pricing", "calc", "Competitor: Selling = CompAvg x (1+Position); Retail = x (1+RetMargin)", "Y", "P", "", "retail-margin leg untested"),
("Frameworks", "Unit Pricing", "calc", "Value Based: Selling = Target Retail / (1+RetMargin); Retail = Target", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "skip-logic", "Method select shows only the chosen block in both channel cards", "Y", "P", "", ""),
("Frameworks", "Unit Pricing", "skip-logic", "Offline card = Wholesale + Retail; Online card = Retail only", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "skip-logic", "Competitor Scope auto-fetches avg & locks read-only", "Y", "N", "", ""),
("Frameworks", "Unit Pricing", "validation", "At least one row required (block deleting last cost row)", "N", "N", "", "rule in neither BRD nor tests"),
("Frameworks", "Unit Pricing", "calc", "Summary aggregates (avg CPU, avg saving, method counts, min/max retail)", "Y", "N", "", ""),

# ---- Schemes & Funding ----
("Frameworks", "Schemes & Funding", "dropdown", "Scheme Master — 19 schemes + Other", "Y", "P", "", "SCH-001 names only CGTMSE"),
("Frameworks", "Schemes & Funding", "dropdown", "Status: Applied / Sanctioned / Disbursed / Rejected / Under Review", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "dropdown", "Eligibility Status: Eligible / Not Eligible / Document Pending", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "dropdown", "Implementation Status: Pending / On hold / Applied / Rejected", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "dropdown", "Log Book Visit Type (7: Site/Bank/DIC-Govt/Phone/Doc Handover/Mentoring/Other)", "P", "N", "brd", "BRD lists a different set (adds Follow-up/Interview; omits Site Visit/Phone Call/Mentoring)"),
("Frameworks", "Schemes & Funding", "calc", "EMI/Month (save-time computed field)", "Y", "Y", "brd", "BRD says flat Loan/Term; implementation computes reducing-balance amortisation (live finding) — reconcile"),
("Frameworks", "Schemes & Funding", "skip-logic", "Intervention toggle ON -> auto-creates Required 'flagged' bridge row; OFF removes", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "skip-logic", "Intervention block on Existing only; Implementation block on Flagged/New only", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "skip-logic", "Bridged scheme name locked/synced from Existing source", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "validation", "Justification required when intervention toggle ON", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "validation", "Application Date <= today; Disbursement >= Application; Loan End > Start", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "validation", "Loan Contribution % range 0-100", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "validation", "Sanctioned/Disbursed/Loan/Outstanding amounts >= 0", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "calc", "Summary rollups (sum sanctioned/disbursed/outstanding/EMI; flagged count; status bar)", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "auto-fill", "Loan repayment fields auto-fetch from Financial module", "Y", "N", "", ""),
("Frameworks", "Schemes & Funding", "validation", "scheme_name is a Link to Funding Scheme Master (rendered as a free-text box)", "P", "N", "", "UI/UX: link field looks like free text (live finding)"),

# ---- Raw Material ----
("Frameworks", "Raw Material", "skip-logic", "Remove Product SKU field (journey-doc change)", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Current Status of Use: Yes / No", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Is It Essential?: Yes / No", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Availability: Easy / Moderate / Difficult", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Procurement Frequency: Daily / Weekly / Monthly / Seasonal", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Procurement Source (existing): Market/Wholesaler/Middleman/Farm/Forest/Online/Others (7)", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "New Source Type (alt): adds Cooperative/FPO/Direct Producer, drops Middleman (9)", "Y", "N", "", "differs from existing-source list"),
("Frameworks", "Raw Material", "dropdown", "Reason for Change: Cost/Quality/Availability/Sustainability/Local/Others (6)", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Quality Trade-off: None / Minor / Moderate / Significant", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Trial Status: Pending/Sample Sourced/Trial Run/Approved/Rejected", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Impl Status (alt src/mat): Pending/In Progress/Completed/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Raw Material", "dropdown", "Impl Status (new material): Pending/In Progress/Completed/On Hold", "Y", "N", "", "'On Hold' vs 'Not Feasible'"),
("Frameworks", "Raw Material", "dropdown", "Resource Category / Type lists", "P", "N", "", "confirm BRD lists resource option values"),
("Frameworks", "Raw Material", "dropdown", "Task Log — 17 RM tasks", "P", "N", "", "full task list not enumerated in BRD"),
("Frameworks", "Raw Material", "validation", "Required: Product Name, Current Status, Material Name, Is Essential, Unit, Qty/Batch, Price/Unit, Batch Size", "Y", "N", "", ""),
("Frameworks", "Raw Material", "skip-logic", "Alt-source toggle auto-creates/removes a row in Required I (bidirectional bridge)", "Y", "N", "", ""),
("Frameworks", "Raw Material", "skip-logic", "Alt-material toggle auto-creates/removes a row in Required II", "Y", "N", "", ""),
("Frameworks", "Raw Material", "skip-logic", "Middleman tag when source=Middleman; Essential tag when Essential=Yes", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Amount Per Batch = Qty/Batch x Price/Unit", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "RM Qty Per Unit = Qty/Batch / Batch Size", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "RM Cost Per Unit = Amount/Batch / Batch Size", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Transport Cost Per Unit = Transport/Trip / Batch Size", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Total Landed Cost/Unit = RM Cost/Unit + Transport/Unit", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Expected Saving/Unit (alt source) = Old Price - New Price", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Existing totals (count, essential count, monthly spend, total RM cost/unit)", "Y", "N", "", ""),
("Frameworks", "Raw Material", "calc", "Cost Before/After + Saving (After = avg new price of Completed only)", "P", "N", "", "confirm 'Completed only' averaging in BRD"),
("Frameworks", "Raw Material", "field", "Cost-calc fields per external Google Sheet (gid=1632694526)", "P", "N", "", "external spec source — confirm fields landed in BRD"),

# ---- Machinery ----
("Frameworks", "Machinery", "dropdown", "Power / Phase: Single Phase / III Phase", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Main Usage Time: Day / Night / Both", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Machinery Condition: Good (10%) / Fair (20%) / Poor (30%)", "Y", "N", "", "drives depreciation rate"),
("Frameworks", "Machinery", "dropdown", "Critical / Non-Critical", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Servicing Required?: Yes / No", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Procurement Status (new): Pending/Vendor Selected/EE Selected/EE Completed/Procured Self (5)", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Intervention flag type: Servicing / Capacity Upgrade", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Impl Status: Pending / In Progress / Completed", "Y", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Resource Category / Type lists", "P", "N", "", ""),
("Frameworks", "Machinery", "dropdown", "Task Log — 16 MC tasks", "P", "N", "", ""),
("Frameworks", "Machinery", "validation", "Required: Name of Machinery, No. of Machinery", "Y", "N", "", ""),
("Frameworks", "Machinery", "skip-logic", "Solarisation + Servicing-required go into Intervention Need banner (journey change)", "Y", "N", "", ""),
("Frameworks", "Machinery", "skip-logic", "Selecting a flagged machine auto-sets flag type + reference (cost/condition)", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Monthly Output = days x hours x Current Capacity/hr", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Capacity Utilization = Current/Max x 100", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Capacity Gap = Max - Current cap/hr", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Depreciation Rate = condition-based (Good 10 / Fair 20 / Poor 30 %)/yr", "Y", "Y", "stale", "MACH test uses straight-line (cost-salvage)/life — contradicts condition-based model"),
("Frameworks", "Machinery", "calc", "Monthly Depreciation = (Cost x Rate) / 12", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Depreciation / Unit = Monthly Dep / Monthly Output", "Y", "P", "", "test formula differs"),
("Frameworks", "Machinery", "calc", "Existing totals (count, investment, output, total dep/unit)", "Y", "N", "", ""),
("Frameworks", "Machinery", "calc", "Dep/Unit Before vs After (existing vs existing+new)", "P", "N", "", ""),

# ---- Human Resource ----
("Frameworks", "Human Resource", "dropdown", "Worker Category: Self / Unpaid Family / Paid Family / Hired Worker", "Y", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Skill Level: Unskilled / Semi-skilled / Skilled / Highly Skilled", "Y", "N", "", "sets GoM threshold"),
("Frameworks", "Human Resource", "dropdown", "Employment Nature: Permanent/Contract/Casual-Daily/Seasonal/Part-time", "Y", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Wage Type: Per Day / Per Month / Per Hour", "Y", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Intervention Type (8: Hire/Wage Revision/Skill Upgrade/Replace/Convert.../Reduce/Compliance)", "Y", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Required Status: Pending/In Progress/Completed/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Resource Category / Type lists", "P", "N", "", ""),
("Frameworks", "Human Resource", "dropdown", "Task Log — 9 HR tasks", "P", "N", "", ""),
("Frameworks", "Human Resource", "validation", "Required: Worker Category, Skill Level, Employment Nature, Wage Type, Wage Rate", "Y", "N", "", ""),
("Frameworks", "Human Resource", "validation", "GoM minimum wage (Unskilled 360 / Semi 410 / Skilled 480 / Highly 550)/day; warn if below", "Y", "P", "", "test fires a generic warning; per-skill thresholds not tested"),
("Frameworks", "Human Resource", "skip-logic", "Labour intervention toggle auto-creates/removes Required I row", "Y", "N", "", ""),
("Frameworks", "Human Resource", "calc", "Total Workers = Male + Female", "Y", "N", "", ""),
("Frameworks", "Human Resource", "calc", "Monthly Labour Cost per worker (per day/month/hour formula) x count", "Y", "N", "", ""),
("Frameworks", "Human Resource", "calc", "Labour Rate / hr", "Y", "N", "", ""),
("Frameworks", "Human Resource", "calc", "GoM compliance from implied daily wage", "Y", "P", "", ""),
("Frameworks", "Human Resource", "calc", "Cost Before/After + Jobs Created (After = Completed only)", "P", "N", "", ""),
("Frameworks", "Human Resource", "field", "New fields per external Google Sheet (gid=879401637)", "P", "N", "", "external spec source — confirm fields landed in BRD"),

# ---- Infrastructure ----
("Frameworks", "Infrastructure", "dropdown", "Water Supply: Own / Locality / PHE / Buys water", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "RWH practiced / willing: Yes / No", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Work location: Home / Separate Workspace", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Space situated (7: house/premises/town/farm/complex/market/others)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Workspace condition: Dilapidated/Poor/Average/Good/Very Good", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Land tenure (7: community/own-purchased/own-inherited/govt-lease/govt-rental/private-rental/others)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Soil condition: Filled / Rocky / Others", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Owner (conditional): Self / Family / Relatives / Others", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "BE Intervention Type: Renovation / Extension / New", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Hill Name: Khasi / Jaintia / Garo Hills", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Building Typology: 3 RCC frames (MSOR) + Kiosks (non-MSOR)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "BE Impl Status (6 stages)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "CE Voltage/Phase: Phase I / Phase III", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "CE Intervention Type (4 lighting/solar combinations)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "EE / CE Impl Status", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Financial project type: PRIME SELCO / Innovation / Scale", "Y", "P", "", "'Scale' not tested"),
("Frameworks", "Infrastructure", "dropdown", "Calc type: Estimation / Final", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "dropdown", "Vendor MS Purpose: Machine / Solar", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "validation", "BE/CE Justification required when intervention flagged", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "validation", "Innovation/Scale editable % must sum to 100% (SELCO+MBMA+LIFCOM+User+Others)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "validation", "Total >= 25,00,000 -> 'Out of policy' warning", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "validation", "Funding gap warning when tranches don't cover cost", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "skip-logic", "MSOR typologies show plinth fields; Kiosks hide them & show manual cost", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "skip-logic", "Owner row shows only for community/own-purchased/own-inherited tenure", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "skip-logic", "Project type toggles slab/EMI/static% vs editable%/validation", "Y", "P", "", "slab/EMI visibility not tested"),
("Frameworks", "Infrastructure", "skip-logic", "BE/CE intervention detail block shown only when toggle on", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "MSOR plinth-rate matrix (9-cell Hill x Typology)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "SQM <-> SQF (factor 10.7639, two-way)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "BE Estimated Cost = Plinth Rate x SQM", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "Rent / Unit = Rent / Units/month -> Unit Pricing", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "Electricity / Unit = Elec / Units/month", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "EE / CE totals", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "Total Infra Cost = BE + EE + CE", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "Slab selection (A<5L / B<10L / C<25L distributions)", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "Funder amounts = Total x slab/editable %", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "calc", "EMI 5yr / 3yr = LIFCOM / 60 or / 36 (flat)", "Y", "P", "", "generic flat EMI only, not the 5yr/3yr split"),
("Frameworks", "Infrastructure", "calc", "Tranche cascade allocation (MBMA->USER->SELCO->LIFCOM; BE->EE->CE; min())", "Y", "N", "", "complex, untested"),
("Frameworks", "Infrastructure", "calc", "Balance card = Disbursed - Paid to vendors", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "auto-fill", "BMC fetches machinery master; Infra fetches machineries from Required section", "Y", "N", "", ""),
("Frameworks", "Infrastructure", "skip-logic", "Building Topology master: add new master renders new field (logic only for 3 values)", "P", "N", "", ""),
]

# ===================== FRAMEWORKS — Product Dev / Compliance / Logistics =====
ROWS += [
# ---- Product Prototyping ----
("Frameworks", "Product Prototyping", "dropdown", "Product (from Product Master)", "P", "N", "", "BRD references master generically, not re-listed"),
("Frameworks", "Product Prototyping", "dropdown", "Implementation Status: Ideating/Iteration/Pilot Implemented/Scale Implementation", "Y", "N", "", ""),
("Frameworks", "Product Prototyping", "dropdown", "Type of Prototyping: Packaging / Product (driver)", "Y", "Y", "", ""),
("Frameworks", "Product Prototyping", "dropdown", "Prototyping Type Name: Packing Master (12) if Packaging else Business Basket (11)", "Y", "Y", "", ""),
("Frameworks", "Product Prototyping", "dropdown", "Resources Category / Type lists", "N", "N", "", "not documented in Prototyping BRD"),
("Frameworks", "Product Prototyping", "dropdown", "Task Log — 17 PP tasks", "P", "N", "", ""),
("Frameworks", "Product Prototyping", "skip-logic", "Type Name list switches by Type of Prototyping; clear on driver change", "Y", "P", "", ""),
("Frameworks", "Product Prototyping", "calc", "Total / Packaging / Product counts; Total + Avg Iterations; Furthest Stage", "Y", "N", "", ""),
("Frameworks", "Product Prototyping", "validation", "Prototype Type = Packaging/Product -> Type Name (NOT Physical/Digital + dimensions/URL)", "Y", "Y", "stale", "PROTO-001 tests Physical/Digital + dimensions/URL — fields do not exist"),

# ---- Product Testing ----
("Frameworks", "Product Testing", "skip-logic", "Remove Product SKU field; remove feedback field (journey change)", "Y", "N", "", ""),
("Frameworks", "Product Testing", "dropdown", "Test Type (14 from master)", "Y", "N", "", ""),
("Frameworks", "Product Testing", "dropdown", "Lab Name (12 from master)", "Y", "N", "", ""),
("Frameworks", "Product Testing", "dropdown", "Implementation Status: Pending/In Progress/Completed/On Hold/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Product Testing", "dropdown", "Resources Category / Type; Task Log 17", "P", "N", "", ""),
("Frameworks", "Product Testing", "validation", "Existing date chain: Sample Deposit <= Test Results", "Y", "Y", "", "TEST-001"),
("Frameworks", "Product Testing", "validation", "Required 3-link chain: Office <= Lab <= Result", "Y", "P", "", "only 2-date Existing chain tested; live finding: no validation fires"),
("Frameworks", "Product Testing", "validation", "Consent unchecked -> reason field required (mandatory)", "Y", "N", "", "F-COND-007 checks reveal only, not the mandatory rule"),
("Frameworks", "Product Testing", "skip-logic", "Consent defaults ON; uncheck reveals reason field", "Y", "Y", "", "F-COND-007"),
("Frameworks", "Product Testing", "skip-logic", "Retesting toggle -> auto-create Required card; bridged Product/Test Type locked", "Y", "N", "", ""),
("Frameworks", "Product Testing", "calc", "Summary aggregates (tests, products, reports, flagged, awaiting, consent counts)", "Y", "N", "", ""),

# ---- Product Standardization ----
("Frameworks", "Standardization", "dropdown", "Standardisation Type (13: Recipe/SOPs/HACCP/GMP/ISO/BRC/Organic/GI/Other)", "Y", "N", "", ""),
("Frameworks", "Standardization", "dropdown", "Resources Category (10) / Type", "Y", "N", "", ""),
("Frameworks", "Standardization", "dropdown", "Implementation Status: Pending/In Progress/Completed/On Hold/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Standardization", "dropdown", "Task Log — 19 PS tasks", "P", "N", "", ""),
("Frameworks", "Standardization", "auto-fill", "Product Sector auto-fetched from product->sector map", "Y", "N", "", ""),
("Frameworks", "Standardization", "validation", "SOP URL must match ^https?:// (Open button gating)", "Y", "Y", "", "SV-URL-001"),
("Frameworks", "Standardization", "skip-logic", "'Being followed?' = No reveals reason textarea", "Y", "Y", "", "F-COND-008"),
("Frameworks", "Standardization", "skip-logic", "Intervention toggle -> bridged Required block (Product/Type locked)", "Y", "N", "", ""),
("Frameworks", "Standardization", "checkbox", "Scope for Standardisation / Approved by Core Team (Required) feed aggregates", "Y", "N", "", ""),
("Frameworks", "Standardization", "calc", "Summary aggregates (SOPs uploaded, followed/not, URL count, types, flagged)", "Y", "N", "", ""),
("Frameworks", "Standardization", "validation", "Model = Yes/No 'being followed' + Impl Status (NOT a Drafted/Reviewed/Approved SOP status)", "Y", "Y", "stale", "STD-001 asserts SOP status Drafted/Reviewed/Approved — no such field"),

# ---- Quality Control ----
("Frameworks", "Quality Control", "data", "Exactly 23 fixed practice questions (count shown n/23)", "Y", "P", "", ""),
("Frameworks", "Quality Control", "scale", "1-5 star scale with legend (1 Not aware … 5 Fully implemented)", "Y", "P", "", ""),
("Frameworks", "Quality Control", "calc", "QC Score = Average Rating = mean of rated stars (2dp); NOT a /115 total or % ring", "Y", "Y", "stale", "QC-001 asserts Total 92/115 (80%) + ring — wrong model; rewrite to mean"),
("Frameworks", "Quality Control", "calc", "Maturity Tier = label[round(avg)] (green>=4, red<=2)", "Y", "N", "", ""),
("Frameworks", "Quality Control", "calc", "Per-practice Gap = Target - Existing (when both rated)", "Y", "N", "", ""),
("Frameworks", "Quality Control", "calc", "Priority badge: gap>=3 Critical / >=2 High / =1 Low / =0 At Target", "Y", "N", "", ""),
("Frameworks", "Quality Control", "calc", "High/Critical gap counts; avg gap; rating distribution (5 buckets)", "Y", "N", "", ""),
("Frameworks", "Quality Control", "calc", "Separate Existing vs Required (Optimized) averages", "Y", "N", "", ""),
("Frameworks", "Quality Control", "skip-logic", "Intervention toggle (Existing) reveals flag note + justification", "Y", "N", "", ""),
("Frameworks", "Quality Control", "dropdown", "Implementation Status (Optimized): Pending/In Progress/Completed/On Hold/Not Feasible", "Y", "N", "", ""),

# ---- Business Registration ----
("Frameworks", "Business Registration", "dropdown", "Registration Master — 28 values in 5 groups + Other", "Y", "P", "", "TC says wrong group name 'Statutory'"),
("Frameworks", "Business Registration", "dropdown", "Registration Level: product level / entrepreneur level", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Existing Status: Received / Not yet Received / Rejected", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Required Status: Applied / Not Yet Applied / Received / Not yet Received / Rejected", "Y", "P", "", ""),
("Frameworks", "Business Registration", "dropdown", "Phase: New Registration / Renewal", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Intervention Type: Renewal / Reapply", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Govt. Certified?: Yes / No", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Resource Category (6) / Type (5)", "Y", "N", "", ""),
("Frameworks", "Business Registration", "dropdown", "Task Log — 12 BR tasks", "Y", "N", "", "FIXED in BRD: now lists the 12 Task-Master tasks (was a generic activity list)"),
("Frameworks", "Business Registration", "validation", "Registration uniqueness (cannot add same twice)", "Y", "N", "", ""),
("Frameworks", "Business Registration", "validation", "Issued Date <= today; Valid Till > Issued Date", "Y", "N", "", "BRD-added; wireframe JS does not enforce"),
("Frameworks", "Business Registration", "validation", "Existing Status mandatory; Justification required when toggle ON", "Y", "N", "", ""),
("Frameworks", "Business Registration", "skip-logic", "Lifetime Validity hides/clears Valid Till", "Y", "N", "", ""),
("Frameworks", "Business Registration", "skip-logic", "Intervention toggle reveals Type+Justification & flag chip", "Y", "N", "", ""),
("Frameworks", "Business Registration", "skip-logic", "Bridge: toggle ON auto-creates locked Required card; Type->Phase; two-way sync; remove un-links", "Y", "N", "", "core mechanic untested"),
("Frameworks", "Business Registration", "calc", "Expiring within 90 days amber / Expired red highlighting", "Y", "N", "", "NT-004 is a 60/30/7-day notify, different rule"),
("Frameworks", "Business Registration", "calc", "Intervention Rate; In Progress; Intervention Needed; aggregate counts", "Y", "N", "", ""),

# ---- Product Compliance ----
("Frameworks", "Product Compliance", "dropdown", "Certification Master — 22 values in 6 groups + Other", "Y", "P", "", "PC-001 adds FSSAI only"),
("Frameworks", "Product Compliance", "field", "'Applicable Product' field", "Y", "N", "brd", "BRD invented this field — NOT in the wireframe"),
("Frameworks", "Product Compliance", "dropdown", "Existing / Required Status; Phase; Intervention Type; Govt Certified?", "Y", "N", "", ""),
("Frameworks", "Product Compliance", "dropdown", "Resource Category / Type (same as Business Reg)", "Y", "N", "", ""),
("Frameworks", "Product Compliance", "dropdown", "Task Log — 12 PC tasks", "P", "N", "brd", "Task-list + column structure (Status/Owner/Due vs wireframe Date/Task/Notes/Attachment) = general Log Book normalization; 5 frameworks share the pattern (see — General row)"),
("Frameworks", "Product Compliance", "validation", "Cert uniqueness; Status mandatory; Issued<=today / Valid Till>Issued", "Y", "N", "", "date rules BRD-only"),
("Frameworks", "Product Compliance", "validation", "Status = Received/Not Yet Received/Rejected (no Active/Expired state)", "Y", "Y", "stale", "PC-002 invents an 'Active' status; expiry not flaggable as written"),
("Frameworks", "Product Compliance", "skip-logic", "Lifetime hides/clears Valid Till; Intervention toggle reveals Type+Justification", "Y", "N", "", ""),
("Frameworks", "Product Compliance", "skip-logic", "Per-card 'Expiring Soon' chip (within 90 days) on Existing header", "Y", "N", "", ""),
("Frameworks", "Product Compliance", "skip-logic", "Bridge + two-way sync (same engine as Business Reg)", "Y", "N", "", ""),
("Frameworks", "Product Compliance", "calc", "90-day expiring amber / expired red; Intervention Rate; aggregate counts", "Y", "P", "", "only 60/30/7-day notify (NT-004) exists"),

# ---- Labels / Marketing Label ----
("Frameworks", "Labels", "dropdown", "Variant Content / Label Status from Product Profile (dropdown, not auto-prepopulate)", "Y", "P", "", "design decision noted at 4774; no Labels exec steps"),
("Frameworks", "Labels", "dropdown", "Add Designer: Designer / Designer 1 / 2 / 3", "Y", "N", "", ""),
("Frameworks", "Labels", "dropdown", "Label Type: Sticker / Tag / Pouch Printing", "Y", "N", "", ""),
("Frameworks", "Labels", "dropdown", "Draft 1/2/3 Status: Pending/Under Review/Redo/Approved/Not Approved", "Y", "N", "", ""),
("Frameworks", "Labels", "dropdown", "Task Log — 14 LABEL tasks", "Y", "N", "", ""),
("Frameworks", "Labels", "skip-logic", "Wine/Alcohol toggle reveals statutory warning banner + ABV field", "Y", "P", "stale", "LBL-001 cites a 'pregnancy warning' field; actual is a fixed 2-line banner + ABV"),
("Frameworks", "Labels", "validation", "ABV required when Alcohol = Yes", "Y", "P", "", "wireframe shows field but no hard JS enforcement"),
("Frameworks", "Labels", "validation", "Statutory warning text is fixed/mandatory (exact 2 lines)", "Y", "N", "", "only test cites wrong text"),
("Frameworks", "Labels", "calc", "Volume = L x B x H (2dp)", "Y", "N", "", ""),
("Frameworks", "Labels", "calc", "Furthest draft reached; latest non-Pending draft -> Implementation Status", "Y", "N", "", ""),
("Frameworks", "Labels", "calc", "Need New Label / No Change / Approved / Redo aggregates", "Y", "N", "", ""),
("Frameworks", "Labels", "validation", "At least one row must remain (delete guard)", "Y", "N", "", ""),
("Frameworks", "Labels", "field", "Master Content: Storyline AI-generate, Manufactured/Marketed by + FSSAI no., Product Pictures", "Y", "N", "", "AI-generate untested; FSSAI-format validation BRD-added"),
("Frameworks", "Labels", "field", "Variant cols: Net Wt, MFD, Best Before (after MFD), MRP, Batch No, Pkg Dims, Photo, 360 video, DPP", "Y", "N", "", "none tested"),

# ---- Packaging ----
("Frameworks", "Packaging", "dropdown", "Type of Packaging: Pouch/Bottle/Box/Jar/Tin", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Material: BOPP/Kraft/PET/Glass/HDPE/Aluminium Foil", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Capacity Unit (gm/ml/kg/L/pcs); Dimension unit (mm/cm/m/in)", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Supports Printing?: Yes/No (drives Print-Ready counts)", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Type of Sealing (multi): Induction/Band/Bottleneck/ROPP/Bottle Cap", "Y", "N", "", "sealing entirely untested"),
("Frameworks", "Packaging", "dropdown", "Impl Status (Intervention): Pending/In Progress/Completed/Replace Existing/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Impl Status (New Pkg): Pending/In Progress/Completed/On Hold", "Y", "N", "", ""),
("Frameworks", "Packaging", "dropdown", "Resources Category / Type lists", "P", "N", "", "BRD omits Print Vendor / Sustainability Reference; Type list missing"),
("Frameworks", "Packaging", "dropdown", "Log Book Activity Type", "P", "N", "", "BRD set shorter (omits Print Trial, Quality Check)"),
("Frameworks", "Packaging", "validation", "Type of Packaging required; numeric >= 0; at least one packaging row", "Y", "N", "", ""),
("Frameworks", "Packaging", "validation", "A variant cannot be selected twice across blocks", "Y", "N", "", "BRD-only; wireframe does not enforce"),
("Frameworks", "Packaging", "skip-logic", "Section III auto-lists an intervention group per distinct Type", "Y", "N", "", ""),
("Frameworks", "Packaging", "skip-logic", "Intervention bridge (toggle -> Required row; two-way) + Justify sync", "Y", "N", "", ""),
("Frameworks", "Packaging", "calc", "Month Total (sum qty x type price); Annual per type; Annual Grand Total -> Unit Pricing", "Y", "P", "", "PKG-001 sums monthly qty only; grand-total feed untested"),
("Frameworks", "Packaging", "calc", "Avg Monthly Qty = Annual / 12", "Y", "N", "", ""),
("Frameworks", "Packaging", "calc", "Saving / Unit = Existing Price - New Price", "Y", "P", "stale", "live finding: saving_per_unit returned 0 (PKG-001); confirm formula/trigger"),

# ---- Logistic Packing ----
("Frameworks", "Logistic Packing", "dropdown", "Type of Packing (10) / Material (10)", "Y", "N", "", ""),
("Frameworks", "Logistic Packing", "dropdown", "Purchase Source (4); Capacity Unit (5); Dimension unit (4); Transport Mode (5)", "Y", "N", "", ""),
("Frameworks", "Logistic Packing", "dropdown", "Damage Observed: None/Minor/Moderate/Severe; Properties (multi: Fragile/Reusable/Waterproof/Cold Chain)", "Y", "N", "", ""),
("Frameworks", "Logistic Packing", "dropdown", "Impl Status (Intervention & New)", "P", "N", "brd", "Standardization decision: BRD uses 'Completed' across all 27 frameworks; logistics wireframes say 'Implemented' — align product or confirm canonical term (BA)"),
("Frameworks", "Logistic Packing", "dropdown", "Resources Category / Log Book Activity Type", "P", "N", "brd", "BRD Category set differs; Log Book omits several activities"),
("Frameworks", "Logistic Packing", "validation", "Type required; at least one row; Stacking Layers >= 1; numeric >= 0", "Y", "N", "", ""),
("Frameworks", "Logistic Packing", "skip-logic", "Intervention bridge + Justify two-way sync; Damage Risk badge", "Y", "N", "", ""),
("Frameworks", "Logistic Packing", "calc", "Month Total; Annual per type + Grand Total -> Logistics Pricing", "Y", "P", "", "LPACK-001 expects a 3-layer transit cost, not the monthly grid"),
("Frameworks", "Logistic Packing", "calc", "Avg Monthly Qty; Saving / Unit (Implemented only feeds After)", "Y", "N", "", ""),

# ---- Logistic Service ----
("Frameworks", "Logistic Service", "dropdown", "Mode of Transport (16)", "Y", "N", "", ""),
("Frameworks", "Logistic Service", "dropdown", "Route Type (Direct/Via Hub/Multi-stop); Direction (Inbound/Outbound/Both)", "Y", "N", "", ""),
("Frameworks", "Logistic Service", "dropdown", "Frequency + multipliers: Daily x30 / Twice-wk x12 / Weekly x4 / Twice-mo x2 / Monthly x1 / 2-mo x0.5", "Y", "P", "", "only Weekly x4 tested; fractional x0.5 untested"),
("Frameworks", "Logistic Service", "dropdown", "Pain Points (7 multi); Delay Frequency (4); Road Connectivity (4); Last Mile (4)", "Y", "P", "", ""),
("Frameworks", "Logistic Service", "dropdown", "Available Services checkbox matrix (4 families, ~21 items)", "P", "N", "", "BRD doesn't enumerate Courier/E-Commerce items"),
("Frameworks", "Logistic Service", "dropdown", "Implementation Status", "P", "N", "brd", "Standardization decision: BRD uses 'Completed' across all 27 frameworks; logistics wireframes say 'Implemented' — align product or confirm canonical term (BA)"),
("Frameworks", "Logistic Service", "dropdown", "Resources Category (6); Log Book Activity (6)", "P", "N", "", "Log Book Activity values not in BRD"),
("Frameworks", "Logistic Service", "validation", "Route Name required; at least one leg row; Leg Cost >= 0", "Y", "N", "", ""),
("Frameworks", "Logistic Service", "skip-logic", "Direction tag; Upgrade bridge + Justify two-way sync", "Y", "N", "", ""),
("Frameworks", "Logistic Service", "calc", "Total Cost Per Trip = sum leg costs", "Y", "Y", "", "F-CALC-027 / LSVC-001 (verified)"),
("Frameworks", "Logistic Service", "calc", "Monthly Cost = Trip Cost x frequency multiplier", "Y", "Y", "", "F-CALC-027"),
("Frameworks", "Logistic Service", "calc", "Annual Cost = Monthly x 12", "Y", "P", "", "LSVC-001 expects 60,000; F-CALC-027 stops at monthly"),
("Frameworks", "Logistic Service", "calc", "Existing totals; Cost After (Implemented only) + saving", "Y", "N", "", ""),
]

# ===================== FRAMEWORKS — Market / Branding / Capability ===========
ROWS += [
# ---- Market Research ----
("Frameworks", "Market Research", "dropdown", "Product; Key Exporting Countries; Key States; Key Selling Locations (masters)", "Y", "N", "", ""),
("Frameworks", "Market Research", "dropdown", "Outlet Type (12); Shelf Placement (6); Origin; Platforms (10); Packing (12)", "Y", "N", "", ""),
("Frameworks", "Market Research", "dropdown", "District master (note 'Eri Bhoi' typo, should be Ri Bhoi)", "Y", "N", "", "typo propagated into BRD too"),
("Frameworks", "Market Research", "dropdown", "Customer-Research Age Group (journey: 16 fine-grained 5-year bands)", "P", "N", "", "wireframe/BRD use 7 broad bands; journey doc is fine-grained"),
("Frameworks", "Market Research", "dropdown", "Occupation (journey: 25 items incl. Business Owner)", "Y", "N", "", "wireframe simplified to 9"),
("Frameworks", "Market Research", "dropdown", "Gender; Location State/District/Block (3 selects, no real cascade in JS)", "Y", "N", "", ""),
("Frameworks", "Market Research", "dropdown", "Competitor Outlet (Offline) / Platform (Online); Resource Category/Type", "P", "N", "", "Resources lists not enumerated in MR BRD"),
("Frameworks", "Market Research", "skip-logic", "Purchase Frequency shown only when 'Have you used the product? = Yes'", "Y", "P", "", "generic F-COND-012, not in section 17"),
("Frameworks", "Market Research", "calc", "Competitor Average Price = mean of non-zero price rows (6 tables)", "Y", "N", "", ""),
("Frameworks", "Market Research", "calc", "6 averages auto-fed to Unit Pricing Competitor-Based", "Y", "P", "", "F-FLOW-007 covers Local-offline only"),
("Frameworks", "Market Research", "calc", "Summary aggregates (products/channels/brands/respondents; SWOT completed)", "Y", "N", "", ""),
("Frameworks", "Market Research", "validation", "Product required; Outlet/Brand name required if entry added; Price >= 0", "Y", "N", "", "negative-price guard BRD-added"),
("Frameworks", "Market Research", "field", "SWOT 4-quadrant grid (Strengths/Weaknesses/Opportunities/Threats)", "Y", "Y", "", "journey doc requires SWOT; grid confirmed present (MR-001)"),

# ---- Customer Analysis ----
("Frameworks", "Customer Analysis", "skip-logic", "Remove row-repeater logic (journey change)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "dropdown", "Demographic: Age/Gender/Family Size/Occupation(25)/Income/Education (multiselect)", "Y", "P", "", "CA-001 picks a couple only"),
("Frameworks", "Customer Analysis", "dropdown", "Geographic: Primary Geography (6); Key Cities; Location Type (multi)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "dropdown", "Psychographic: Values&Lifestyle (15); Buying Motivation (12)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "dropdown", "Behavioural: Purchase Behaviour (12); Usage Rate (8); Loyalty (10); Occasion (12)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "dropdown", "Primary / Secondary Customers; Target Segment; Market Readiness; Impl Status", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "dropdown", "Resource Category (7) / Type (5)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "skip-logic", "Intervention toggle reveals Justification; Status chip mirrors Impl Status", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "calc", "Summary comparison Existing vs Required (match by product; readiness/impl aggregates)", "Y", "N", "", ""),
("Frameworks", "Customer Analysis", "validation", "Product required; no duplicate chip values", "Y", "P", "", "generic UI-CHIP-001 only"),

# ---- Market Linkage ----
("Frameworks", "Market Linkage", "dropdown", "Channel Type (Online/Offline); Selling Mode (B2B/B2C/D2C/Exhibition)", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "dropdown", "Location (Block Master); Identified By (Ground/Core/Entrepreneur)", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "dropdown", "Product Name (nested) -> Product SKU (cascade); Impl Status; Source tag", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "skip-logic", "SKU populated by selected Product ('Select Product first'); Upgrade toggle reveals Justification", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "calc", "Avg Revenue/Month = Price x Units; Annual = x12; Annual Total = Price x total units", "Y", "P", "", "F-CALC-022"),
("Frameworks", "Market Linkage", "calc", "Sales Tracker Revenue = Quantity x Price; month + grand totals", "Y", "P", "", "F-CALC-023; live: Revenue needs a priced Product (ML-001 blocked)"),
("Frameworks", "Market Linkage", "calc", "Channel status-chip rollup (all Completed / any Not Feasible / any In Progress)", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "calc", "Summary aggregates (online/offline, modes, best channel, unique products)", "Y", "N", "", ""),
("Frameworks", "Market Linkage", "calc", "Net revenue after commission", "N", "Y", "stale", "ML-001 tests vol x price x (1-15%) — NO commission field exists in spec"),

# ---- Promotions ----
("Frameworks", "Promotions", "dropdown", "Type: Offline / Online", "Y", "N", "", ""),
("Frameworks", "Promotions", "dropdown", "Frequency: Daily / Weekly / Monthly / Yearly", "Y", "N", "", ""),
("Frameworks", "Promotions", "dropdown", "Implementation Status (Pending/In Progress/Completed/Not Feasible)", "Y", "N", "", ""),
("Frameworks", "Promotions", "dropdown", "Resource Category (8) / Type (5)", "Y", "N", "", ""),
("Frameworks", "Promotions", "field", "Handled by / Suggested Handled by (free text)", "Y", "N", "", "BRD over-specifies a richer doctype not in wireframe"),
("Frameworks", "Promotions", "skip-logic", "Intervention toggle reveals Justification; req-impl onchange refresh", "Y", "N", "", ""),
("Frameworks", "Promotions", "calc", "Summary aggregates (online/offline split, frequency counts, status counts)", "Y", "N", "", ""),
("Frameworks", "Promotions", "calc", "Cost per reach = budget / reach", "N", "Y", "stale", "PROMO-001 tests it — NO budget/reach/cost fields exist (live finding)"),

# ---- Branding Identity ----
("Frameworks", "Branding Identity", "field", "Brand / Logo / Business Card clubbed into one framework (3 tabs), combined task list", "Y", "N", "", "journey change; BRD captures clubbing"),
("Frameworks", "Branding Identity", "dropdown", "Approval (Entrepreneur / Core Team): Approved / Pending / Rejected", "Y", "P", "", "BRAND-002 tests dual-approve, not the 3 values / Rejected path"),
("Frameworks", "Branding Identity", "dropdown", "Logo Designer: Designer A / B / AI Generated", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "dropdown", "Business Card Designer: Designer A / B (NO AI Generated)", "Y", "N", "", "difference from Logo track untested"),
("Frameworks", "Branding Identity", "dropdown", "Resources Category (Brand/Logo/Card/General); Resources Type", "Y", "N", "", "Verified present in BRD (Type = Template/Reference/Guideline/Example) — earlier 'missing' flag was incorrect"),
("Frameworks", "Branding Identity", "dropdown", "Task Log — 24 fixed tasks", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "skip-logic", "'Need New Brand Name?' ON -> New Brand Name + Justification required", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "skip-logic", "'Need New Logo?' ON -> Justification required", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "skip-logic", "Draft Versions sequential (Draft 2/3 Pending until prior done; max 3)", "Y", "P", "", "BRAND-001 uploads 3 but doesn't test sequential lock"),
("Frameworks", "Branding Identity", "permission", "Only Core Team assigns Designer (dropdown = designer-role users); field team views", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "validation", "Designer required before uploading drafts; >=1 draft before approval; dual approval to finalise", "Y", "P", "", "BRAND-002 happy-path only"),
("Frameworks", "Branding Identity", "validation", "At least one row required (Resources & Task Log)", "N", "N", "", ""),
("Frameworks", "Branding Identity", "field", "Market Scope chips (Local/State | National), single-select default", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "auto-fetch", "Enterprise Name, Storyline, Media Folder, Card Content auto-fetched read-only", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "field", "Multiselect file upload with upload/view buttons (not links); logo shows EP profile snapshot", "Y", "N", "", ""),
("Frameworks", "Branding Identity", "calc", "Summary hero + track cards mirror Brand/Logo/Card tabs", "Y", "N", "", ""),

# ---- Marketing Brochure ----
("Frameworks", "Marketing Brochure", "dropdown", "Brochure Type (multi 5: Single/Multi-Product/Tri-fold/Bi-fold/Flyer)", "Y", "P", "", "BR-001 picks products, not the Type list"),
("Frameworks", "Marketing Brochure", "dropdown", "Per-product Brochure Type (size 3, mirrors master)", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "dropdown", "Market Scope; Designer (A/B/AI); Print Format (A4/A5/DL/Custom)", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "dropdown", "Draft 1/2/3 Status (Pending/Under Review/Redo/Approved/Not Approved)", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "dropdown", "Task Log — 12 brochure tasks", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "skip-logic", "syncBrochureTypeOptions per-product to match master multiselect", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "validation", "Product Name required when a Brochure Type selected; Page Count whole >= 1; Need New -> Justify", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "validation", "At least one row required (3 tables)", "N", "N", "", ""),
("Frameworks", "Marketing Brochure", "field", "Dimensions L/B/H separate + Volume calc; MOQ relabel; Retail+Wholesale fetched from Unit Pricing", "Y", "N", "", "journey change; price field removed"),
("Frameworks", "Marketing Brochure", "field", "Product Snapshot fetched from product; existing-brochure HD field; multiselect attachments", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "field", "Storyline 'Generate with AI' (Apoorva)", "Y", "N", "", ""),
("Frameworks", "Marketing Brochure", "calc", "Aggregates (Total Existing, Need New, No Change, Products Included; furthest draft; flags)", "Y", "N", "", ""),

# ---- Pitch Deck ----
("Frameworks", "Pitch Deck", "dropdown", "Implementation Status: Pending/In Progress/Implemented/Not Feasible", "Y", "N", "", ""),
("Frameworks", "Pitch Deck", "dropdown", "Log Book Visit Type (Site/Phone/Pitch Rehearsal/Investor Meeting/Mentoring/Workshop/Other)", "Y", "N", "", "FIXED in BRD: Visit Type now matches the wireframe's 7 values"),
("Frameworks", "Pitch Deck", "dropdown", "Task Log Status: Pending/In Progress/Completed/Blocked", "N", "N", "brd", "'Blocked' option missing from BRD"),
("Frameworks", "Pitch Deck", "skip-logic", "Need-a-deck toggle ON -> flags intervention, activates Required workspace", "Y", "N", "", ""),
("Frameworks", "Pitch Deck", "skip-logic", "Video link 'Open' button only when URL entered; deck 'View' only after file attached", "Y", "N", "", ""),
("Frameworks", "Pitch Deck", "validation", "Deck upload .pdf/.ppt/.pptx only; video must be valid URL; Entrepreneur unique", "Y", "N", "", ""),
("Frameworks", "Pitch Deck", "validation", "Log Book at least one row", "N", "N", "", ""),
("Frameworks", "Pitch Deck", "calc", "11 slides; Completion % = filled/11; Slides Filled/Empty (fill = non-empty textarea)", "Y", "P", "stale", "PD-001 phrases slide state as Drafted/Reviewed/Final, not fill-based"),
("Frameworks", "Pitch Deck", "calc", "Slide Breakdown groups (Story 3 / Business 3 / Market 2 / Team-Ask 3)", "N", "N", "", ""),
("Frameworks", "Pitch Deck", "calc", "Status badge colour map; Last Updated auto-set on edit", "Y", "N", "", ""),
("Frameworks", "Pitch Deck", "field", "Task Log seed: 18 tasks across 3 phases", "Y", "N", "", ""),

# ---- Digital Literacy ----
("Frameworks", "Digital Literacy", "dropdown", "Platform/Skill (9 from master)", "Y", "P", "", "DL-001 says '9 platforms' but lists none"),
("Frameworks", "Digital Literacy", "scale", "5-star skill legend (1 No knowledge … 5 Proficient); 1-5 (no 0; X clears)", "Y", "P", "stale", "DL-001 says '0-5' scale — wrong"),
("Frameworks", "Digital Literacy", "calc", "Average Skill Level = sum stars / rated count (2dp); 0 excluded", "Y", "N", "stale", "DL-001 invents Readiness = avg x 20 = 100% + radar chart — not in spec"),
("Frameworks", "Digital Literacy", "skip-logic", "Has smartphone/laptop/internet = No -> 'required?' question", "Y", "N", "", ""),
("Frameworks", "Digital Literacy", "dropdown", "Existing Access checkboxes; device 'Needed' + status (4); Required Impl Status (5)", "Y", "N", "", ""),
("Frameworks", "Digital Literacy", "skip-logic", "Intervention toggle -> bridged Required row (platform locked); two-way delete sync", "Y", "N", "", ""),
("Frameworks", "Digital Literacy", "calc", "Skill Change = Target - Existing; Device Gap; Summary aggregates", "Y", "N", "", ""),
("Frameworks", "Digital Literacy", "dropdown", "Log Book Activity Type (6); Task Log (10 fixed)", "Y", "N", "", ""),

# ---- Capacity Building ----
("Frameworks", "Capacity Building", "dropdown", "Skill Type: Soft / Technical (mandatory)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "dropdown", "Skill Area: Soft (8) / Technical (10) lists", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "skip-logic", "Skill Type -> Skill Area filter (Soft shows soft optgroup; clears technical)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "dropdown", "Training Format (6); Completion Status (4, mandatory); Skill Retention (4); Applied (3)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "dropdown", "Behaviour Change (4); Improvement Seen (6); Time Since (4); Gap Severity (4)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "dropdown", "Skill Levels (4); Intervention Type (6); Assigned To (4); Impl Status (6)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "skip-logic", "Re-training toggle -> bridges training to Required I (name/area/justification locked)", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "scale", "Post-Training scorecard: 6 dimensions x 1-5 stars (legend None..Excellent)", "Y", "P", "", "CB-001 tests past-training only, not the 6-dim scorecard"),
("Frameworks", "Capacity Building", "validation", "End Date >= Start Date; Required Level >= Current Level", "Y", "N", "", ""),
("Frameworks", "Capacity Building", "calc", "Summary roll-ups (Past/Required/Capacity/Status cards; gap = Target-Current)", "Y", "P", "", ""),

# ---- Business Plan Canvas ----
("Frameworks", "Business Plan Canvas", "field", "9 canvas blocks (Key Partners … Revenue Streams)", "Y", "P", "", "tested only generically (BPC-001)"),
("Frameworks", "Business Plan Canvas", "calc", "Quadrant grouping (Infra 3 / Offering 1 / Customer 3 / Financial 2)", "Y", "N", "", ""),
("Frameworks", "Business Plan Canvas", "calc", "Completion % = filled / 9 x 100", "Y", "N", "", ""),
("Frameworks", "Business Plan Canvas", "validation", "Blocks filled MANUALLY; cross-module refs are read-only links (no auto-copy)", "Y", "Y", "stale", "BPC-001 asserts auto-population from upstream DFs — contradicts spec"),
("Frameworks", "Business Plan Canvas", "calc", "Value Prop Set flag (empty Value Prop flagged)", "Y", "N", "", ""),
("Frameworks", "Business Plan Canvas", "dropdown", "Resources Category (10) / Type (6); Task Log (17)", "Y", "N", "", ""),
("Frameworks", "Business Plan Canvas", "validation", "At least one resource row", "P", "N", "", ""),
("Frameworks", "Business Plan Canvas", "skip-logic", "7 cross-module reference pills (read-only links + redirect)", "Y", "N", "", ""),
]

# ===================== ENTREPRENEUR PROFILE ==================================
ROWS += [
("Entrepreneur Profile", "EP Profile", "field", "Rural E Champ Score (Int, permlevel 1 = Core Team only)", "P", "Y", "brd", "BRD says 'filled by Fellow'; repo + journey = Core Team only"),
("Entrepreneur Profile", "EP Profile", "field", "Selection Attachment (permlevel 1)", "Y", "P", "stale", "EP-021 'Final Selection blocked without attachment' — no such validation"),
("Entrepreneur Profile", "EP Profile", "dropdown", "Final Selection: Incubated / Supported (permlevel 1)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "validation", "final_selection mandatory once rural_e_champ_score entered", "N", "N", "", "real repo rule, undocumented + untested"),
("Entrepreneur Profile", "EP Profile", "field", "Status model: activity_status (Active/Inactive) + final_selection (Incubated/Supported); NO stored 'MET'", "Y", "Y", "brd", "BRD/tests treat 'MET' as a stored status; repo has none"),
("Entrepreneur Profile", "EP Profile", "journey", "Prioritisation: frameworks auto-listed (priority 0), reorder, dashboard cards realign on save", "Y", "P", "", ""),
("Entrepreneur Profile", "EP Profile", "skip-logic", "Prioritisation tab shown only when Incubated/Supported", "Y", "P", "", "gating not explicitly tested"),
("Entrepreneur Profile", "EP Profile", "field", "Priority-table 'Applicable?' checkbox", "Y", "Y", "brd", "No 'applicable' field in repo; rows auto-seeded, add/remove hidden — BRD & EP-022 invented it"),
("Entrepreneur Profile", "EP Profile", "validation", "Duplicate framework AND duplicate priority blocked", "P", "P", "", "dup-priority not in BRD/tests; EP-023 add-twice can't run"),
("Entrepreneur Profile", "EP Profile", "validation", "Priority value: Int, 0 is the valid default", "N", "Y", "stale", "EP-024 asserts 0/-1 rejected & >10 warning — not implemented"),
("Entrepreneur Profile", "EP Profile", "validation", "Entrepreneur Name unique globally (case-sensitive)", "Y", "Y", "stale", "EP-006 says 'unique case-insensitive within cohort' — wrong scope"),
("Entrepreneur Profile", "EP Profile", "validation", "Future DOB blocked (datepicker maxDate = today)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "validation", "DOB min-age 14 / max-age 100", "N", "Y", "stale", "EP-007 / section 11 assert rules not implemented in repo"),
("Entrepreneur Profile", "EP Profile", "validation", "Phone required + format (default +91-)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "validation", "Email format", "Y", "P", "", ""),
("Entrepreneur Profile", "EP Profile", "validation", "District / Block / Village required to save", "P", "Y", "stale", "repo: non-mandatory, auto-populated from Program Access; EP-005 'Village required' wrong"),
("Entrepreneur Profile", "EP Profile", "permission", "FA sees all blocks, edits only own block (server-forced from Program Access)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "skip-logic", "Block filtered by District; Village by Block (link_filters)", "P", "N", "", ""),
("Entrepreneur Profile", "EP Profile", "auto-fill", "Raw Materials from Product Profile -> Raw Material framework rows", "Y", "N", "", "journey-mandated; zero tests"),
("Entrepreneur Profile", "EP Profile", "auto-fill", "Process&Machinery existing machines -> Machinery framework Existing tab", "Y", "N", "", "journey-mandated; zero tests"),
("Entrepreneur Profile", "EP Profile", "field", "Dashboard: product photo cards clickable -> Product Profile", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "calc", "Dashboard framework completion 'Not started / Completed xN' from logs; summary popup %", "Y", "P", "", "repetition count + popup % not tested"),
("Entrepreneur Profile", "EP Profile", "field", "GPS Geolocation (location)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "validation", "KYC: Aadhaar (Verhoeff), PAN, EPIC, Bank patterns", "P", "Y", "", "EPIC & Bank patterns not in BRD"),
("Entrepreneur Profile", "EP Profile", "field", "Networking: Mentor Master registry doctype", "P", "Y", "build", "Mentor Master NOT built in repo; PRD specifies it; tests assume it exists"),
("Entrepreneur Profile", "EP Profile", "field", "Networking: Introduction child (mentor/contact_type/introduced_by/date/objective; fetch_from mentor)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "dropdown", "Networking contact_type: Mentor / Network Contact", "P", "N", "", ""),
("Entrepreneur Profile", "EP Profile", "dropdown", "Networking meeting_status (Not Yet Met/Awaiting Response/Scheduled/In Progress/Completed)", "P", "P", "stale", "EP-035 uses 'Pending' — no such option"),
("Entrepreneur Profile", "EP Profile", "field", "Networking: Meeting Log standalone + auto-sync count/last/next/outcome", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "dropdown", "Networking outcome controlled vocabulary (7 values)", "N", "N", "", "not in BRD or tests"),
("Entrepreneur Profile", "EP Profile", "calc", "avg_rating from 10 ratings (repo scales to 0-100)", "P", "P", "", "BRD says 'mean of 10'; repo = (total/max)*5*10 — mismatch, exact value untested"),
("Entrepreneur Profile", "EP Profile", "skip-logic", "18 needs-support flags with dependent note fields (depends_on reveal)", "Y", "N", "", ""),
("Entrepreneur Profile", "EP Profile", "dropdown", "EP Landscape filters: District/Block/Cohort/Sector/Business Basket/Product Name", "Y", "P", "", "Business Basket / Product Name map filters not tested"),
("Entrepreneur Profile", "EP Profile", "dropdown", "Sector: repo = hardcoded 3-option Select", "P", "Y", "brd", "journey/BRD/tests assume a Sector master cascading to Business Basket; repo has neither"),
("Entrepreneur Profile", "EP Profile", "field", "Cohort (Link, standard filter)", "Y", "Y", "", ""),
("Entrepreneur Profile", "EP Profile", "field", "Autoname EP-.{name}-.#####; after save -> Profile Dashboard", "Y", "Y", "", ""),
]

# ===================== PRODUCT FORM =========================================
ROWS += [
("Product Form", "Product Profile", "dropdown", "Product Status: New / Existing", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Sector (6 options)", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Business Basket (8 options)", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Product Type (7 options)", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Product Name required; Link to Product Master (autocomplete)", "Y", "P", "stale", "PR-002 treats it as free text + invents a duplicate-per-EP rule"),
("Product Form", "Product Profile", "auto-fetch", "Entrepreneur chip auto-fetched", "Y", "N", "", ""),
("Product Form", "Product Profile", "field", "Product Snapshot (textarea)", "Y", "P", "", "labelled 'Description' in PR-001"),
("Product Form", "Product Profile", "field", "Product Image (attach + view)", "Y", "N", "", ""),
("Product Form", "Product Profile", "auto-fill", "Ingredients = read-only pills fetched from Raw Material framework (edit product to add)", "Y", "N", "", "journey core rule; zero tests"),
("Product Form", "Product Profile", "field", "USP (textarea)", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Shelf Life Tested: Yes / No", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Shelf Life Duration = free-text Data ('12 months')", "Y", "Y", "stale", "PR-003 asserts positive integer; reject 0/-3/'twelve' — field is free text"),
("Product Form", "Product Profile", "skip-logic", "Available Months = 12-row checkbox table (TRUE/FALSE); >=1 to generate Tracker", "Y", "Y", "stale", "PR-004 describes a chip group / All-months quick-select — wrong control"),
("Product Form", "Product Profile", "calc", "SKU = VARIANT-SUBVARIANT-WEIGHT-UNIT (strip, UPPERCASE, drop empty); read-only", "Y", "P", "stale", "PR-008/014 use APIC-HHF-250G-001 master-expansion format"),
("Product Form", "Product Profile", "dropdown", "Variant Status: Existing / New", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Variant Name required (feeds SKU)", "Y", "P", "", ""),
("Product Form", "Product Profile", "field", "Sub Variant (free text, feeds SKU)", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Net Weight Float > 0 (feeds SKU)", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Unit (variant): g/kg/ml/L/pcs/bundle (Unit Master)", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Dimensions L x B x H (3 floats + unit)", "Y", "N", "", ""),
("Product Form", "Product Profile", "calc", "Volume = L x B x H (unit^3); read-only", "Y", "N", "", ""),
("Product Form", "Product Profile", "auto-fetch", "Retail Price (variant) read-only, fetched from Unit Pricing", "Y", "P", "", ""),
("Product Form", "Product Profile", "validation", "Wholesale < Unit Cost / Retail < Wholesale rules", "N", "Y", "stale", "PR-009/010 assert pricing rules on fields that don't exist (pricing lives in Unit Pricing)"),
("Product Form", "Product Profile", "skip-logic", "Process Flow steps: drag-reorder, auto-renumber, +Add/Remove", "Y", "Y", "", ""),
("Product Form", "Product Profile", "field", "Step Detail required", "Y", "P", "", ""),
("Product Form", "Product Profile", "auto-fill", "Machine Used (status Existing) -> Machinery framework Existing tab", "Y", "N", "stale", "journey: machines -> Machinery; PR-007/RAWMAT-002 wrongly route machines -> Raw Materials"),
("Product Form", "Product Profile", "dropdown", "Machine Status (Existing/Required); Implemented? (Yes/No); Step Status (Pending/In Progress/Done)", "Y", "N", "", ""),
("Product Form", "Product Profile", "skip-logic", "Agri By-Product: Yes shows agri block, No greys out", "Y", "N", "", ""),
("Product Form", "Product Profile", "dropdown", "Land Ownership (4); Production Unit (5); Capacity Units (8, Unit Master)", "Y", "N", "", ""),
("Product Form", "Product Profile", "validation", "Area Covered Float > 0; Existing/Aspiring Capacity Int >= 0", "Y", "N", "", ""),
("Product Form", "Product Profile", "field", "Sowing/Harvesting/Processing Season month grids (Jan-Dec bools)", "Y", "N", "", ""),
("Product Form", "Product Profile", "skip-logic", "Is Product Seasonal? Yes -> Season month grid", "Y", "N", "", ""),
("Product Form", "Product Profile", "calc", "Monthly Production Tracker: rows = Available Months; Selling Price from variant Retail", "Y", "N", "", ""),
("Product Form", "Product Profile", "calc", "Tracker Revenue = Qty x Selling Price; row + annual totals", "Y", "N", "", ""),
("Product Form", "Product Profile", "field", "Products show as clickable photo cards on profile dashboard", "Y", "Y", "", ""),
("Product Form", "Product Profile", "calc", "General logic: calc fields show formula; fetched fields show source + redirect", "Y", "P", "", ""),
("Product Form", "Product Profile", "field", "Tabs = Details / Variants / Process Flow / Production Capacity (no Financials/Compliance)", "Y", "Y", "stale", "PR-001/015 reference Financials/Compliance tabs that don't exist"),
("Product Form", "Product Profile", "auto-fill", "Data-flow: Ingredients -> RM; Machines -> Machinery", "Y", "N", "", "FIXED in BRD: removed the erroneous machines->Raw-Materials data-flow row (now routes machines -> Machinery only)"),
]



